export const LIST_GET_ALL_PENDING = '@LIST/GET_ALL_PENDING';
export const LIST_GET_ALL_SUCCESSFUL = '@LIST/GET_ALL_SUCCESSFUL';
export const LIST_GET_ALL_REJECTED = '@LIST/GET_ALL_REJECTED';
export const LIST_GET_NEXT_PAGE_PENDING = '@LIST/LIST_GET_NEXT_PAGE_PENDING';
export const LIST_GET_NEXT_PAGE_SUCCESSFUL = '@LIST/LIST_GET_NEXT_PAGE_SUCCESSFUL';
export const LIST_GET_NEXT_PAGE_REJECTED = '@LIST/LIST_GET_NEXT_PAGE_REJECTED';
