export const LIST_GET_ALL_PENDING = '@LIST/GET_ALL_PENDING';
export const LIST_GET_ALL_SUCCESSFUL = '@LIST/GET_ALL_SUCCESSFUL';
export const LIST_GET_ALL_REJECTED = '@LIST/GET_ALL_REJECTED';
export const LIST_SET_ITEM_PREVIEW = '@LIST/SET_ITEM_PREVIEW';
export const LIST_CLEAR_ITEM_PREVIEW = '@LIST/CLEAR_ITEM_PREVIEW';
